Master
MSchiavi/TrueStatValues pull request #2
Opened 2024-08-16 18:13 UTC by Xorban

Pre patch fix

2024-08-16 18:55 UTC, MSchiavi requested changes

2024-08-16 18:55 UTC, MSchiavi commented on .vscode/settings.json
> +{
Can we remove this from the PR

2024-08-16 18:55 UTC, MSchiavi commented on TrueStatValues
This shouldn't be here as well

2024-08-16 18:55 UTC, MSchiavi commented on TrueStatValues.toc
> +<<<<<<< HEAD
Is this for the icon?

2024-08-16 18:55 UTC, MSchiavi commented on TrueStatvalues.tga
I am guessing this is the icon you were letting me know about?

2024-08-16 19:12 UTC, Xorban commented on .vscode/settings.json
> +{
yes we can

2024-08-16 19:12 UTC, Xorban commented on .vscode/settings.json
> +{
> Can we remove this from the PR

yes we can

2024-08-17 02:20 UTC, MSchiavi approved these changes

2024-08-17 02:20 UTC, merged